import { createHash } from 'node:crypto'
import { escapeHtml } from '@/lib/email/escape'

export function createVerificationEmail({ name, url }: { name: string; url: string }) {
  const safeName = escapeHtml(name || 'there')
  const safeUrl = escapeHtml(url)
  const plainName = name || 'there'
  const idempotencyKey = `verification/${createHash('sha256').update(url).digest('hex').slice(0, 32)}`

  return {
    idempotencyKey,
    subject: 'Welcome to EfoKa.ma — verify your email',
    text: `Welcome to EfoKa.ma, ${plainName}.\n\nYou created an EfoKa.ma account. Verify your email to activate your commerce workspace:\n${url}\n\nThis link expires soon. If you did not create this account, you can safely ignore this email.`,
    html: `<!doctype html><html lang="en"><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#edf5ef;color:#17352a;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf5ef"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px"><tr><td style="padding:18px 8px 22px"><div style="font-size:23px;font-weight:800;letter-spacing:-1px;color:#0a2b22">EfoKa<span style="color:#7ba63a">.ma</span></div><div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#527567;margin-top:7px">Commerce operations, made clearer</div></td></tr><tr><td style="background:#0a2b22;border-radius:24px 24px 0 0;padding:34px 30px;color:#fff"><div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#9de3c1;font-weight:700">Your workspace is waiting</div><h1 style="font-size:32px;line-height:1.12;letter-spacing:-1px;margin:16px 0 0;color:#fff">Welcome to EfoKa.ma</h1></td></tr><tr><td style="background:#fff;border:1px solid #dce8df;border-top:0;border-radius:0 0 24px 24px;padding:34px 30px;box-shadow:0 12px 30px rgba(28,68,48,.08)"><p style="font-size:17px;line-height:1.6;margin:0 0 12px">Hi ${safeName},</p><p style="font-size:16px;line-height:1.65;color:#587064;margin:0 0 26px">You created an EfoKa.ma account. Verify your email to connect your stores, understand your performance, and operate from one live workspace.</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="border-radius:12px;background:#c6f06e"><a href="${safeUrl}" style="display:inline-block;padding:15px 22px;color:#082c23;font-weight:800;text-decoration:none;font-size:15px">Verify my email</a></td></tr></table><div style="border-top:1px solid #e7eee8;margin-top:30px;padding-top:22px"><p style="font-size:13px;line-height:1.65;color:#6c8278;margin:0"><strong style="color:#345b49">Security note</strong><br>This verification link expires soon and can only be used to confirm this registration. If you did not create an EfoKa.ma account, no action is needed.</p><p style="font-size:13px;line-height:1.65;color:#6c8278;margin:18px 0 0">Button not working? Copy and paste this secure link into your browser:</p><p style="font-size:12px;line-height:1.6;word-break:break-all;color:#527567;margin:7px 0 0">${safeUrl}</p></div></td></tr><tr><td align="center" style="padding:22px 10px;color:#71877c;font-size:12px;line-height:1.6">EfoKa.ma · Make every connected store easier to operate.<br>© ${new Date().getFullYear()} EfoKa.ma · <a href="${escapeHtml(process.env.APP_URL ?? '#')}" style="color:#527567">Help center</a></td></tr></table></td></tr></table></body></html>`,
  }
}
