'use client'

import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, CheckCircle2, CircleAlert, Clock3, Package, RefreshCw, ShoppingBag, Sparkles, Truck, Users } from 'lucide-react'

type Props = { productCount: number; catalogState: string; summary: { status: string; syncedAt?: string; metrics?: { products: number; inventory: number; lowStock: number; catalogValue: number } }; onNavigate: (view: 'Integrations' | 'Orders' | 'Inbox') => void }

const trend = [
  { day: 'Apr 11', revenue: 5400, orders: 54 }, { day: 'Apr 12', revenue: 6200, orders: 62 }, { day: 'Apr 13', revenue: 7900, orders: 79 },
  { day: 'Apr 14', revenue: 9600, orders: 96 }, { day: 'Apr 15', revenue: 8400, orders: 84 }, { day: 'Apr 16', revenue: 12600, orders: 126 },
  { day: 'Apr 17', revenue: 14600, orders: 146 }, { day: 'Apr 18', revenue: 16600, orders: 166 }, { day: 'Apr 19', revenue: 19000, orders: 190 },
  { day: 'Apr 20', revenue: 22000, orders: 220 }, { day: 'Apr 21', revenue: 24800, orders: 248 },
]
const cities = [{ name: 'Casablanca', orders: 187, revenue: 'MAD98.4K', rate: '96.2%' }, { name: 'Rabat', orders: 112, revenue: 'MAD58.7K', rate: '94.6%' }, { name: 'Marrakech', orders: 86, revenue: 'MAD44.1K', rate: '93.0%' }, { name: 'Tangier', orders: 61, revenue: 'MAD32.5K', rate: '91.8%' }, { name: 'Agadir', orders: 44, revenue: 'MAD22.9K', rate: '90.9%' }]
const channels = [{ name: 'WhatsApp', value: 42, color: '#16847b' }, { name: 'Storefront', value: 31, color: '#6b9b5e' }, { name: 'Instagram', value: 18, color: '#d68162' }, { name: 'Other', value: 9, color: '#b9c7bd' }]

export default function AdvancedOverview({ productCount, catalogState, summary, onNavigate }: Props) {
  const [range, setRange] = useState('Last 30 days')
  const [activeMetric, setActiveMetric] = useState<'revenue' | 'orders'>('revenue')
  const [liveStatus, setLiveStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const live = summary.metrics
  useEffect(() => { const controller = new AbortController(); fetch('/api/commerce/analytics', { signal: controller.signal, cache: 'no-store' }).then((response) => { if (!response.ok) throw new Error('unavailable'); setLiveStatus('ready') }).catch(() => setLiveStatus('error')); return () => controller.abort() }, [])
  const totalRevenue = useMemo(() => trend.reduce((sum, item) => sum + item.revenue, 0), [])
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] text-[#8d9990]"><span>Workspace</span><span>/</span><span className="text-[#4d7b55]">Overview</span></div><h2 className="text-[24px] font-semibold tracking-[-0.05em] text-[#173b2b]">Commerce performance</h2><p className="mt-1 text-[12px] text-[#89948c]">A live read on revenue, demand, operations, and customer momentum.</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded-xl border border-[#dfe7df] bg-white px-3 py-2 text-[11px] font-semibold text-[#5d6e63] outline-none"><option>Last 30 days</option><option>Last 7 days</option><option>This quarter</option></select><button onClick={() => onNavigate('Integrations')} className="flex items-center gap-2 rounded-xl bg-[#235337] px-3 py-2 text-[11px] font-semibold text-white"><Sparkles size={14} />Connect data</button></div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total orders" value="2.31k" trend="+104.2%" detail="+1.18k vs previous period" icon={ShoppingBag} /><Metric label="Gross revenue" value="MAD573.47k" trend="+97.3%" detail="+MAD282.84k vs previous period" icon={ArrowUpRight} /><Metric label="Delivered ratio" value="94%" trend="+11.8%" detail="+9.72 pts vs previous period" icon={Truck} /><Metric label="Returned ratio" value="2.8%" trend="-64.5%" detail="-5.1 pts vs previous period" icon={RefreshCw} negative /></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniMetric label="Catalog value" value={live ? `${live.catalogValue.toLocaleString()} USD` : 'MAD194.2K'} detail={live ? `${live.inventory.toLocaleString()} units in stock` : 'Live product inventory'} /><MiniMetric label="Active products" value={catalogState === 'loading' ? '…' : productCount.toLocaleString()} detail="Across connected channels" /><MiniMetric label="Low-stock watch" value={live ? live.lowStock.toString() : '12'} detail="Products need attention" warning /><MiniMetric label="Avg order value" value="MAD530.67" detail="366 completed orders" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.45fr_0.8fr]">
      <div className="rounded-2xl border border-[#e2e9e2] bg-white p-5 shadow-[0_8px_28px_rgba(30,73,43,.04)]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="text-[13px] font-semibold text-[#173b2b]">Sales over time</h3><p className="mt-1 text-[11px] text-[#89948c]">Performance for {range.toLowerCase()} across connected channels.</p></div><div className="flex rounded-lg bg-[#f3f7f2] p-1"><button onClick={() => setActiveMetric('revenue')} className={`rounded-md px-3 py-1.5 text-[10px] font-semibold ${activeMetric === 'revenue' ? 'bg-white text-[#235337] shadow-sm' : 'text-[#89948c]'}`}>Revenue</button><button onClick={() => setActiveMetric('orders')} className={`rounded-md px-3 py-1.5 text-[10px] font-semibold ${activeMetric === 'orders' ? 'bg-white text-[#235337] shadow-sm' : 'text-[#89948c]'}`}>Orders</button></div></div><div className="mt-5 h-[245px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4b9b72" stopOpacity={0.3} /><stop offset="100%" stopColor="#4b9b72" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf1ed" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: '#9aa49c' }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: '#9aa49c' }} tickFormatter={(value) => activeMetric === 'revenue' ? `${value / 1000}k` : value} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e1e9e1', fontSize: 11 }} formatter={(value) => { const numericValue = Number(value ?? 0); return activeMetric === 'revenue' ? [`MAD${numericValue.toLocaleString()}`, 'Revenue'] : [numericValue, 'Orders'] }} /><Area type="monotone" dataKey={activeMetric} stroke="#287858" strokeWidth={3} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div><div className="mt-4 grid grid-cols-3 border-t border-[#edf1ed] pt-4"><Stat label="Total revenue" value={`MAD${(totalRevenue / 1000).toFixed(1)}K`} /><Stat label="Total orders" value="1,431" /><Stat label="Conversion" value="8.42%" /></div></div>
      <div className="rounded-2xl border border-[#e2e9e2] bg-white p-5 shadow-[0_8px_28px_rgba(30,73,43,.04)]"><div className="flex items-start justify-between"><div><h3 className="text-[13px] font-semibold text-[#173b2b]">Channel mix</h3><p className="mt-1 text-[11px] text-[#89948c]">Where orders are coming from.</p></div><button onClick={() => onNavigate('Integrations')} className="text-[#4d8b61]" aria-label="Open integrations"><ArrowUpRight size={16} /></button></div><div className="relative mt-2 h-[185px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={channels} dataKey="value" nameKey="name" innerRadius={55} outerRadius={78} paddingAngle={3}>{channels.map((channel) => <Cell key={channel.name} fill={channel.color} />)}</Pie><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e1e9e1', fontSize: 11 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-2xl font-semibold tracking-[-.05em] text-[#173b2b]">2.31k</span><span className="text-[10px] text-[#89948c]">orders</span></div></div><div className="space-y-2">{channels.map((channel) => <div key={channel.name} className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-[#68776d]"><span className="size-2 rounded-full" style={{ backgroundColor: channel.color }} />{channel.name}</span><span className="font-semibold text-[#173b2b]">{channel.value}%</span></div>)}</div></div>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="rounded-2xl border border-[#e2e9e2] bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-[13px] font-semibold text-[#173b2b]">City performance</h3><p className="mt-1 text-[11px] text-[#89948c]">Delivery success and revenue concentration.</p></div><button onClick={() => onNavigate('Orders')} className="text-[11px] font-semibold text-[#287858]">View orders</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-[11px]"><thead className="border-b border-[#edf1ed] text-[9px] uppercase tracking-[.12em] text-[#9aa49c]"><tr><th className="pb-3">City</th><th className="pb-3 text-right">Orders</th><th className="pb-3 text-right">Revenue</th><th className="pb-3 text-right">Rate</th></tr></thead><tbody>{cities.map((city, index) => <tr key={city.name} className="border-b border-[#f0f3ef] last:border-0"><td className="py-3 font-medium text-[#263d2e]"><span className="mr-2 text-[#a4afa7]">{index + 1}</span>{city.name}</td><td className="py-3 text-right text-[#5d6e63]">{city.orders}</td><td className="py-3 text-right font-medium text-[#263d2e]">{city.revenue}</td><td className="py-3 text-right font-semibold text-[#16847b]">{city.rate}</td></tr>)}</tbody></table></div></div><div className="rounded-2xl border border-[#e2e9e2] bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-[13px] font-semibold text-[#173b2b]">Operations pulse</h3><p className="mt-1 text-[11px] text-[#89948c]">What needs attention today.</p></div><span className={`size-2 rounded-full ${liveStatus === 'ready' ? 'bg-[#43a66e]' : 'bg-[#e5a24d]'}`} /></div><div className="mt-4 space-y-3"><Pulse icon={CheckCircle2} label="Delivery performance" detail="94% delivered on time" tone="good" /><Pulse icon={CircleAlert} label="Low-stock products" detail={`${live?.lowStock ?? 12} items below threshold`} tone="warn" /><Pulse icon={Clock3} label="Awaiting confirmation" detail="18 COD orders need review" tone="neutral" /><Pulse icon={Users} label="Inbox response time" detail="Average 4m 12s this week" tone="good" /></div></div></section>
  </div>
}
function Metric({ label, value, trend, detail, icon: Icon, negative = false }: { label: string; value: string; trend: string; detail: string; icon: typeof Package; negative?: boolean }) { return <div className="rounded-2xl border border-[#e2e9e2] bg-white p-5 shadow-[0_8px_28px_rgba(30,73,43,.04)]"><div className="flex items-start justify-between"><p className="text-[11px] font-medium text-[#7f8c82]">{label}</p><span className="flex size-8 items-center justify-center rounded-lg bg-[#eef5ed] text-[#43764c]"><Icon size={15} /></span></div><div className="mt-3 flex items-center gap-2"><p className="text-[23px] font-semibold tracking-[-.05em] text-[#173b2b]">{value}</p><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${negative ? 'bg-[#edf5ed] text-[#16847b]' : 'bg-[#eaf6f3] text-[#16847b]'}`}>{trend}</span></div><div className="mt-3 flex items-center gap-2 text-[10px] text-[#89948c]"><span className="size-1.5 rounded-full bg-[#16847b]" />{detail}</div></div> }
function MiniMetric({ label, value, detail, warning = false }: { label: string; value: string; detail: string; warning?: boolean }) { return <div className="rounded-2xl border border-[#e2e9e2] bg-white p-4"><p className="text-[11px] text-[#7f8c82]">{label}</p><p className="mt-2 text-[19px] font-semibold tracking-[-.04em] text-[#173b2b]">{value}</p><p className={`mt-1 text-[10px] ${warning ? 'text-[#b87942]' : 'text-[#89948c]'}`}>{detail}</p></div> }
function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-[#89948c]">{label}</p><p className="mt-1 text-[16px] font-semibold text-[#173b2b]">{value}</p></div> }
function Pulse({ icon: Icon, label, detail, tone }: { icon: typeof CheckCircle2; label: string; detail: string; tone: 'good' | 'warn' | 'neutral' }) { return <div className="flex items-center gap-3 rounded-xl bg-[#f7faf6] p-3"><span className={`flex size-8 items-center justify-center rounded-lg ${tone === 'good' ? 'bg-[#e6f5e8] text-[#3c935e]' : tone === 'warn' ? 'bg-[#fff2e2] text-[#bd7c3d]' : 'bg-[#edf1f0] text-[#738278]'}`}><Icon size={15} /></span><div><p className="text-[11px] font-semibold text-[#294433]">{label}</p><p className="mt-0.5 text-[10px] text-[#89948c]">{detail}</p></div></div> }
